using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PDL.ReportService.Entites.VM.ReportVM
{
    public class ApplicationFormDataModel
    {
        public int Fid { get; set; }
        public string Creator { get; set; }
        public string FICode { get; set; }
        public string CustName { get; set; }
        public string Guardian { get; set; }
        public string ResidentialAddress { get; set; }
        public DateTime DOB { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int NoOfDependencies { get; set; }
        public string Education { get; set; }
        public string SkillCertification { get; set; }
        public string AadharID { get; set; }
        public string VoterID { get; set; }
        public string DrivingLicense { get; set; }
        public string PanNo { get; set; }
        public string Mobile { get; set; }
        public string EmailID { get; set; }
        public string LoanPurpose { get; set; }
        public string LoanPeriod { get; set; }
        public string BankIFSC { get; set; }
        public decimal LoanAmount { get; set; }
        public string Caste { get; set; }
        public string Pincode { get; set; }
        public string GroupCode { get; set; }
        public string ProfilePic { get; set; }
        public string GPic { get; set; }
        public string RelationWithBorrower { get; set; }
        public string BankAddress { get; set; }
        public string BankName { get; set; }
        public string Fi_BankName { get; set; }
        public string BankAccountNo { get; set; }
        public int NoOfChildren { get; set; }
        public decimal FamilyMonthlyIncome { get; set; }
        public string IsMarried { get; set; }
        public string Telephone { get; set; }
        public string VillageName { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictName { get; set; }
       //ublic List<FirsteSignVM> firstESign { get; internal set; }

        public string NomineAadhar { get; set; }
        public string NomineGender { get; set; }
        public string NominePhone { get; set; }
        public string NomineVoter { get; set; }
        public string GuardianName { get; set; }
        public string NomineAge { get; set; }
        public string NomineName { get; set; }
        public DateTime NomineDOB { get; set; }
        public string IsHouseRentedOrOwned { get; set; }
        public string NoOfAdult { get; set; }
        public string EarningFamMem { get; set; }
        public string FamMemIncome { get; set; }
        public string Occupation { get; set; }
        public string SpecialSocialCategory { get; set; }
        public decimal sanctionAmount { get; set; }
        public string smcode { get; set; }
        public string CSOName { get; set; }
        public string BranchCode { get; set; }
        public string Income { get; set; }
        public string BorrowerEducation { get; set; }
        public string IsBorrowerHandicap { get; set; }
        public string GR_AdhaarId { get; set; }
        public string GR_Name { get; set; }
        public string GR_PIC { get; set; }
        public string GR_AGE { get; set; }
        public string GR_GENDER { get; set; }
        public string GR_PHONE { get; set; }
        public string GR_GUARDIAN { get; set; }
        public string GR_RelationWithBorrower { get; set; }
        public string GR_VOTER { get; set; }
        public string GR_DOB { get; set; }
        public string Years_in_business { get; set; }
        public string Religion { get; set; }
        public string CustomerId { get; set; }
    }

    public class  HouseVisitReportModel
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public int FId { get; set; }
        public long FICode { get; set; }
        public string Guardian { get; set; }
        public string LoanAmount { get; set; }
        public string CurrentPhone { get; set; }
        public string PPhone { get; set; }
        public string Code { get; set; }
        public DateTime Date { get; set; }
        public string Creator { get; set; }
        public string BranchName { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string GroupCode { get; set; }
        public string HouseType { get; set; }
        public string Center { get; set; }
        public string EmpCode { get; set; }
        public string Addr { get; set; }
        public string BusinessVerification { get; set; }
        public string Image { get; set; }
        public string ResidenceType { get; set; }
        public string HouseMonthlyRent { get; set; }
        public string DistanceToBranch { get; set; }
        public string TimeToReachBranch { get; set; }
        public string TotalExperienceOccupation { get; set; }
        public string FamilyMemberFromPaisalo { get; set; }
        public string MonthlyIncome { get; set; }
        public string MonthlySales { get; set; }
        public string WorkExperience { get; set; }
        public string loansufficientwithdebt { get; set; }
        public string SeasonDependency { get; set; }
        public string IsvalidLocation { get; set; }
        public string CPFlifeStyle { get; set; }
        public string CpfPOAddressVerify { get; set; }
        public string PhotoIdVerification { get; set; }
        public string CurrentAddressprof { get; set; }
        public string HasbandWifeAgeverificaton { get; set; }
        public string ParmanentAddressPincode { get; set; }
        public string StampOnPhotocopy { get; set; }
        public string LastLoanVerification { get; set; }
        public string LoanUsagePercentage { get; set; }
        public string AbsentReasonInCentermeeting { get; set; }
        public string RepaymentFault { get; set; }
        public string LoanreasonVerification { get; set; }
        public string IsAppliedAmountAppropriate { get; set; }
        public string FamilyAwarenessaboutloan { get; set; }
        public string IsloanAppropriateforBusiness { get; set; }
        public string Businessaffectedourrelation { get; set; }
        public string Repayeligiblity { get; set; }
        public string Cashflowoffamily { get; set; }
        public string IncomeMatchedwithprofile { get; set; }
        public string BorrowersupportedGroup { get; set; }
        public string ComissionDemand { get; set; }
        public string GroupReadyToVilay { get; set; }
        public string GroupHasBloodRelation { get; set; }
        public string OverlimitLoanBorrowfromgroup { get; set; }
        public string workingPlaceVerification { get; set; }
        public string StockVerification { get; set; }
        public string GuarantorRelation { get; set; }
        public string GuarantorPhone { get; set; }
        public string GuarantorAge { get; set; }
        public string GuarantorName { get; set; }
        public string RelationofInterviewer { get; set; }
        public string NetmonthlyincomeAfterproposedloan { get; set; }
        public string Totalmonthlyhouseholdexpenses { get; set; }
        public string Netmonthlyincomeotherfamilymembers { get; set; }
        public string Relationearningmember { get; set; }
        public string feedbacknearbyresident { get; set; }
        public string Mobilereferenceperson2 { get; set; }
        public string Namereferenceperson2 { get; set; }
        public string Mobilereferenceperson1 { get; set; }
        public string Namereferenceperson1 { get; set; }
        public string Totalmonthlyexpensesofoccupation { get; set; }
        public string Residing_with { get; set; }
        public string Residential_Stability { get; set; }
        public string UnderstandInsaurancePolicy { get; set; }
        public string VerifyExternalLoan { get; set; }
        public string UnderstandsFaultPolicy { get; set; }
        public string toatlDebtUnderLimit { get; set; }
        public string IsWorkingPlaceValid { get; set; }
        public string workingPlacedescription { get; set; }
        public string Path { get; set; }
        public string CSOName { get; set; }
        public string NameofInterviewed { get; set; }

    }

    public class SecondEsignVM
    {
        public int F_Id { get; set; }
        public string CustName { get; set; }
        public string Gaurdian { get; set; }
        public string EmailId { get; set; }
        public string Creator { get; set; }
        public string Age { get; set; }
        public DateTime? DOB { get; set; }
        public string NOB { get; set; }
        public string Gender { get; set; }
        public string VoterId { get; set; }
        public string AadharId { get; set; }
        public string DrivingLicense { get; set; }
        public string LoanReason { get; set; }
        public string Cast { get; set; }
        public string FCast { get; set; }
        public string BranchCode { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string Telephone { get; set; }
        public string Bank_Name { get; set; }
        public string BankAddress { get; set; }
        public string BankIFSC { get; set; }
        public string ResidentialAddress { get; set; }
        public decimal? SanctionedAmt { get; set; }
        public int? LoanDuration { get; set; }
        public DateTime? SanctionedDate { get; set; }
        public DateTime? TodayDate { get; set; }
        public DateTime? DateHead { get; set; }
        public decimal? RateOfInterestBlended { get; set; }
        public decimal? ServiceTax { get; set; }
        public decimal? SchIrr { get; set; }
        public decimal? RateOfBlended { get; set; }
        public decimal? RateOfBank { get; set; }
        public decimal? RateOfNBFC { get; set; }
        public decimal? Period { get; set; }
        public decimal? UcoEmi { get; set; }
        public string HouseOwner { get; set; }
        public string Travelling { get; set; }
        public string OtherExpense { get; set; }
        public string Expense { get; set; }
        public string Health { get; set; }
        public string Rent { get; set; }
        public string Fooding { get; set; }
        public string Mobile { get; set; }
        public string SmCode { get; set; }
        public string Code { get; set; }
        public string PPh2 { get; set; }
        public int? NoOfChildren { get; set; }
        public int? OtherDependents { get; set; }
        public decimal? RatePercent { get; set; }
        public string GroupCode { get; set; }
        public string BranchName { get; set; }
        public string PanNO { get; set; }
        public string Pin { get; set; }
        public string Religion { get; set; }
        public string IsMarried { get; set; }
        public decimal? Income { get; set; }
        public decimal? FutureIncome { get; set; }
        public string FamIncomeSource { get; set; }
        public decimal? FamMonthlyIncome { get; set; }
        public string Education { get; set; }
        public string EDUCATION_CODE { get; set; }
        public string DIST_NAME { get; set; }
        public string SUB_DIST_NAME { get; set; }
        public string StateName { get; set; }
        public decimal? AgricultureIncome { get; set; }
        public decimal? RentalIncome { get; set; }
        public decimal? PensionIncome { get; set; }

        public string Rent_of_House { get; set; }
        public string Picture { get; set; }
        public decimal? Amount { get; set; }
        public decimal? NbfcRate { get; set; }
        public decimal? Rate { get; set; }
        public decimal? LoanAmt { get; set; }
        public decimal? loanamt5 { get; set; }
        public decimal? InsuranceAmount { get; set; }
        public decimal? ProcessingFeeSBICase { get; set; }
        public decimal? ProcessingFee { get; set; }
        public int? SpendOnChildren { get; set; }
        public int? Live_In_Present_Place { get; set; }
        public int? TotalDependents { get; set; }
    }
}
